SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE TB_PRICE_MODIFIER (
	ID INTEGER NOT NULL,
	NAME VARCHAR2( 25 CHAR ) NOT NULL,
	MULTIPLIER DOUBLE NOT NULL
);

ALTER TABLE TB_PRICE_MODIFIER ADD CONSTRAINT PK_PRICE_MODIFIER PRIMARY KEY ( ID );

CREATE SEQUENCE SEQ_PRICE_MODIFIER START WITH 1;

INSERT INTO TB_PRICE_MODIFIER ( ID, NAME, MULTIPLIER ) VALUES ( SEQ_PRICE_MODIFIER.NEXTVAL, 'INSTRUMENT1', 1.5 );
INSERT INTO TB_PRICE_MODIFIER ( ID, NAME, MULTIPLIER ) VALUES ( SEQ_PRICE_MODIFIER.NEXTVAL, 'INSTRUMENT2', 2.5 );
INSERT INTO TB_PRICE_MODIFIER ( ID, NAME, MULTIPLIER ) VALUES ( SEQ_PRICE_MODIFIER.NEXTVAL, 'INSTRUMENT3', 4.5 );